### ISSUE TITLE
Displaying Keepass titles instead of usernames on panel

### ISSUE THREAD

**Issue by c20h** [abextm/keepassxc-runelite#10]
Would it be possible to make it so that on the panel the plugin displays the title that is entered into Keepass entry rather than the actual login name?

The plugin is already able to read the title from the program so I would assume that this is doable.

**Comment by abextm** [comment]
If you hide usernames on the login screen it will show the title

**Comment by c20h** [comment]
> If you hide usernames on the login screen it will show the title

Mate, that is so good. Thanks and also huge thanks for replying so fast!
