### ISSUE TITLE
No logins found for "https://secure.runescape.com"

### ISSUE THREAD

**Issue by cmsu224** [abextm/keepassxc-runelite#3]
![](https://i.gyazo.com/e47342dceb1fcfca2f73b257c6c98a53.png)
I have my logins correctly setup on KeePassXC but, it looks like the plugin isn't able to detect it.

![image](https://user-images.githubusercontent.com/14130954/104943539-e73c2b00-5983-11eb-858a-bba308c35cda.png)

**Comment by abextm** [comment]
If you go to [the login page on runescape.com](https://secure.runescape.com/m=weblogin/loginform?theme=runescape&mod=www&ssl=1&dest=community) with the keepassxc browser extension installed does it show your account?

**Comment by cmsu224** [comment]
Yes, it's working fine on the browser.

**Comment by abextm** [comment]
Hmm, I'm not sure why KeePassXC is telling me there are no credentials, but then giving them to the browser. What are your browser integration settings in KeePassXC and KeePassXC version?

**Comment by cmsu224** [comment]
I'm running version 2.6.3 and here are my settings:
![image](https://user-images.githubusercontent.com/14130954/105071575-c8589a00-5a52-11eb-9013-76d0936b92a1.png)

The browser extensions are working fine and I was able to create a new key through runelite but, I can't figure out why its not finding any password entries.
![image](https://user-images.githubusercontent.com/14130954/105071970-4452e200-5a53-11eb-99af-acc989043903.png)

Is there any kind of debug procedure or statement written in RunLite's log files that gives more info?

**Comment by cmsu224** [comment]
Here's whats in the log:

2021-01-19 13:25:12 [KeePassXCSocketConnection] INFO  a.os.keepassxc.proto.KeePassXCSocket - failed to read keyring
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:194)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:248)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:132)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:59)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by abextm** [comment]
fixed in 687ff2dd17328100dc86f94b667256facb0e12c0 / v1.0.2
