### ISSUE TITLE
Little suggestion

### ISSUE THREAD

**Issue by ReinierAarnink1996** [abextm/keepassxc-runelite#4]
Hey. This plugin is really nice. I prefer it over Profiles. The only thing I can talk about that perhaps can be improved is that after I clicked my username and everything fills up, it goes to another plugin. This is the ge plugin or sometimes screen markers, for me. I'd rather have it fold the plugin itself. Like this: http://prntscr.com/ymrozi

How to replicate:
http://prntscr.com/ymrgpv
http://prntscr.com/ymrkkb
http://prntscr.com/ymrmvm

**Comment by nseguin42** [comment]
Would love to see this fixed. If it auto-opens the sidebar it should auto-close it after.

**Comment by Jin-Jiyunsun** [comment]
I would like to add my support that after the this plugin is done on the loginscreen that it would be nice if there was an option to make it close the sidebar instead of leaving it open on a different tab.

**Comment by thebubbsy** [comment]
came here to request this too, preferably default back to whatever panel you had open last would be ideal. thanks for plugin.

**Comment by abextm** [comment]
fixed in runelite/runelite@8118d9d7b9f8129625b148a7b8d46cb735a66890
